from typing import Annotated

from langgraph.graph import MessagesState

from .invest_debate import InvestDebateState
from .risk_debate import RiskDebateState


class TradingAnalysisState(MessagesState):
    """Global state for the market analysis and debate graph."""

    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    enable_fundamentals: Annotated[
        bool, "Toggle to enable/disable fundamentals analysis (False for Gold/Crypto)"
    ]
    current_price: Annotated[
        float, "Current market price of the asset (injected by Market Analyst)"
    ]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[
        dict, "Structured JSON plan generated by the Trader"
    ]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[
        dict, "Final structured JSON decision made by the Portfolio Manager"
    ]
    past_context: Annotated[
        str,
        "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)",
    ]
